export const ERROR = "ERROR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//account reducers
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
export const LOAD_BALANCE = "LOAD_BALANCE";

export const SET_ACCOUNT = "SET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

export const LOAD_PPOL_INFO = "LOAD_PPOL_INFO";

export const DISAPPROVE_TOKENS = "DISAPPROVE_TOKENS";
export const RESET_USER_STAKE = "RESET_USER_STAKE";

export const SHOW_POOL_LOADING = "SHOW_POOL_LOADING";
export const HIDE_POOL_LOADING = "HIDE_POOL_LOADING";

export const CHANGE_NETWORK = "CHANGE_NETWORK";

export const LOAD_PBR_MARKET_DATA = "LOAD_PBR_MARKET_DATA";
export const LOAD_STAKE_POOL = "LOAD_STAKE_POOL";
export const ALLOWANCE_UPDATE = "ALLOWANCE_UPDATE";

export const GET_USER_STAKE_DATA = "GET_USER_STAKE_DATA";
