export const ERROR = "ERROR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//account reducers
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
export const LOAD_BALANCE = "LOAD_BALANCE";
export const LOAD_PBR_BALANCE = "LOAD_PBR_BALANCE";
export const LOAD_BITE_BALANCE = "LOAD_BITE_BALANCE";
export const LOAD_CLF365_BALANCE = "LOAD_CLF365_BALANCE";
export const LOAD_CORGIB_BALANCE = "LOAD_CORGIB_BALANCE";
export const LOAD_PWAR_BALANCE = "LOAD_PWAR_BALANCE";
export const LOAD_PUN_BALANCE = "LOAD_PUN_BALANCE";
export const LOAD_SHOE_BALANCE = "LOAD_SHOE_BALANCE";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

//stake reducers
export const LOAD_PPOL_INFO = "LOAD_PPOL_INFO";
export const LOAD_BSC_POOL = "LOAD_BSC_POOL";
// export const CHECK_ALLOWANCE = "CHECK_ALLOWANCE";
export const APPROVE_PBR_TOKENS = "APPROVE_PBR_TOKENS";
export const APPROVE_BITE_TOKENS = "APPROVE_BITE_TOKENS";
export const APPROVE_CORGIB_TOKENS = "APPROVE_CORGIB_TOKENS";
export const APPROVE_PWAR_TOKENS = "APPROVE_PWAR_TOKENS";
export const APPROVE_CLF365_TOKENS = "APPROVE_CLF365_TOKENS";
export const APPROVE_PUN_TOKENS = "APPROVE_PUN_TOKENS";
export const APPROVE_SHOE_TOKENS = "APPROVE_SHOE_TOKENS";
export const APPROVE_WELT_TOKENS = "APPROVE_WELT_TOKENS";
export const APPROVE_GRAV_TOKENS = "APPROVE_GRAV_TOKENS";
export const APPROVE_DEFLY_TOKENS = "APPROVE_DEFLY_TOKENS";

export const DISAPPROVE_TOKENS = "DISAPPROVE_TOKENS";
export const RESET_USER_STAKE = "RESET_USER_STAKE";

export const STAKE_PBR_TOKENS = "STAKE_PBR_TOKENS";
export const STAKE_BITE_TOKENS = "STAKE_BITE_TOKENS";
export const UNSTAKE_PBR_TOKENS = "UNSTAKE_PBR_TOKENS";
export const UNSTAKE_BITE_TOKENS = "UNSTAKE_BITE_TOKENS";
export const STAKE_CORGIB_TOKENS = "STAKE_CORGIB_TOKENS";
export const UNSTAKE_CORGIB_TOKENS = "UNSTAKE_CORGIB_TOKENS";
export const STAKE_CLF365_TOKENS = "STAKE_CLF365_TOKENS";
export const STAKE_PUN_TOKENS = "STAKE_PUN_TOKENS";
export const STAKE_SHOE_TOKENS = "STAKE_SHOE_TOKENS";
export const STAKE_WELT_TOKENS = "STAKE_WELT_TOKENS";
export const STAKE_GRAV_TOKENS = "STAKE_GRAV_TOKENS";
export const STAKE_DEFLY_TOKENS = "STAKE_DEFLY_TOKENS";

export const STAKE_PWAR_TOKENS = "STAKE_PWAR_TOKENS";

export const SHOW_POOL_LOADING = "SHOW_POOL_LOADING";
export const HIDE_POOL_LOADING = "HIDE_POOL_LOADING";
export const RESET_PBR_TOKEN = "RESET_PBR_TOKEN";
export const RESET_BITE_TOKEN = "RESET_BITE_TOKEN";
export const RESET_CORGIB_TOKEN = "RESET_CORGIB_TOKEN";
export const RESET_PWAR_TOKEN = "RESET_PWAR_TOKEN";
export const RESET_CLF365_TOKEN = "RESET_CLF365_TOKEN";
export const RESET_PUN_TOKEN = "RESET_PUN_TOKEN";
export const RESET_SHOE_TOKEN = "RESET_SHOE_TOKEN";
export const RESET_WELT_TOKEN = "RESET_WELT_TOKEN";
export const RESET_GRAV_TOKEN = "RESET_GRAV_TOKEN";
export const RESET_DEFLY_TOKEN = "RESET_DEFLY_TOKEN";

export const CHANGE_NETWORK = "CHANGE_NETWORK";
