export const ERROR = "ERROR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//account reducers
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
export const LOAD_BALANCE = "LOAD_BALANCE";
export const SET_ACCOUNT = "SET_ACCOUNT";

//stake reducers
export const LOAD_PPOL_INFO = "LOAD_PPOL_INFO";
// export const CHECK_ALLOWANCE = "CHECK_ALLOWANCE";
export const APPROVE_TOKENS = "APPROVE_TOKENS";
export const DISAPPROVE_TOKENS = "DISAPPROVE_TOKENS";
export const RESET_USER_STAKE = "RESET_USER_STAKE";
export const GET_USER_STAKE = "GET_USER_STAKE";
export const STAKE_TOKENS = "STAKE_TOKENS";
export const UNSTAKE_TOKENS = "UNSTAKE_TOKENS";
export const SHOW_POOL_LOADING = "SHOW_POOL_LOADING";
export const HIDE_POOL_LOADING = "HIDE_POOL_LOADING";
